# CoP weight
# Field default value 1.0
float64 cop

# Weight for a proxy of the exerted torques
# Field default value 1.0
float64 torques

# Weight on the control amplitude
# Field default value 1.0
float64 control_multipliers

# Weight on the final control value
# Field default value 1.0
float64 final_control

# Weight on the maximum control amplitude
# Field default value 1.0
float64 max_control_multiplier

# Weight on the final state error
# Field default value 10.0
float64 final_state

# Weight on the control variation
# Field default value 1.0
float64 control_variations

# Weight on the difference from the desired phase duration
# Field default value 1.0
float64 durations_difference


