# Position and orientation of the left foot. In case of SWING state this is ignored
geometry_msgs/Pose left_foot_pose

# Position and orientation of the left foot. In case of SWING state this is ignored
geometry_msgs/Pose right_foot_pose

# Phase desired duration
# Field default value 0.8
float64 desired_duration

# Phase minimum duration
# Field default value 0.5
float64 minimum_duration

# Phase maximum duration
# Field default value 2.0
float64 maximum_duration


