# Position and orientation of the left foot. In case of SWING state this is ignored
geometry_msgs/Pose left_foot_pose

# Position and orientation of the left foot. In case of SWING state this is ignored
geometry_msgs/Pose right_foot_pose

# Phase desired duration
float64 desired_duration 0.8

# Phase minimum duration
float64 minimum_duration 0.5

# Phase maximum duration
float64 maximum_duration 2.0