# CoP weight
float64 cop

# Weight for a proxy of the exerted torques
float64 torques

# Weight on the control amplitude
float64 control_multipliers

# Weight on the final control value
float64 final_control

# Weight on the maximum control amplitude
float64 max_control_multiplier

# Weight on the final state error
float64 final_state

# Weight on the control variation
float64 control_variations

# Weight on the difference from the desired phase duration
float64 durations_difference