# CoP weight
float64 cop 1.0

# Weight for a proxy of the exerted torques
float64 torques 1.0

# Weight on the control amplitude
float64 control_multipliers 1.0

# Weight on the final control value
float64 final_control 1.0

# Weight on the maximum control amplitude
float64 max_control_multiplier 1.0

# Weight on the final state error
float64 final_state 10.0

# Weight on the control variation
float64 control_variations 1.0

# Weight on the difference from the desired phase duration
float64 durations_difference 1.0