#ifndef __controller_msgs__msg__KinematicsStreamingToolboxStatusMessage__idl__
#define __controller_msgs__msg__KinematicsStreamingToolboxStatusMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet KSTSTATE_SLEEP =
      0;

      const octet KSTSTATE_CALIBRATION =
      1;

      const octet KSTSTATE_VALIDATION =
      2;

      const octet KSTSTATE_STREAMING =
      3;


      /**
       * This message is part of the IHMC whole-body inverse kinematics module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::KinematicsStreamingToolboxStatusMessage_")
      struct KinematicsStreamingToolboxStatusMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Indicates the current state of the toolbox:
         */
        @defaultValue(value=255)
        octet current_state;
      };
    };
  };
};

#endif
