#ifndef __controller_msgs__msg__QuadrupedTeleopMessage__idl__
#define __controller_msgs__msg__QuadrupedTeleopMessage__idl__

#include "controller_msgs/msg/./QuadrupedXGaitSettingsPacket_.idl"
#include "geometry_msgs/msg/./Vector3_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC quadruped controller API.
       * This message sends a desired stepping velocity to the step teleop module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::QuadrupedTeleopMessage_")
      struct QuadrupedTeleopMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Flag to request walking or standing. If true the robot will start or continue to walk with the specified parameters.
         * If false the robot will stop walking and the parameters below are ignored.
         */
        boolean request_walk;
        /**
         * Defines if the step list is adjustable
         */
        @defaultValue(value=True)
        boolean are_steps_adjustable;
        /**
         * Desired planar velocities in m/s and rad/s. X and Y correspond to forward and lateral velocities. Z corresponds to yaw velocity
         */
        geometry_msgs::msg::dds::Vector3 desired_velocity;
        /**
         * Desired xgait settings
         */
        controller_msgs::msg::dds::QuadrupedXGaitSettingsPacket x_gait_settings;
      };
    };
  };
};

#endif
