#ifndef __controller_msgs__msg__StepUpPlannerVector2__idl__
#define __controller_msgs__msg__StepUpPlannerVector2__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::StepUpPlannerVector2_")
      struct StepUpPlannerVector2
      {
        double x;
        double y;
      };
    };
  };
};

#endif
