#ifndef __controller_msgs__msg__StepUpPlannerRespondMessage__idl__
#define __controller_msgs__msg__StepUpPlannerRespondMessage__idl__

#include "controller_msgs/msg/./CenterOfMassTrajectoryMessage_.idl"
#include "controller_msgs/msg/./FootstepDataListMessage_.idl"
#include "controller_msgs/msg/./StepUpPlannerPhaseResult_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::StepUpPlannerRespondMessage_")
      struct StepUpPlannerRespondMessage
      {
        /**
         * The various trajectories are split in every different phase
         */
        sequence<controller_msgs::msg::dds::StepUpPlannerPhaseResult, 20> phases_result;
        /**
         * A collection of messages containing the CoM trajectory (0 elements in case not required in the parameters message)
         */
        sequence<controller_msgs::msg::dds::CenterOfMassTrajectoryMessage, 20> com_messages;
        /**
         * A collection of messages containing the footsteps (0 elements in case not required in the parameters message)
         */
        sequence<controller_msgs::msg::dds::FootstepDataListMessage, 20> foostep_messages;
      };
    };
  };
};

#endif
